# This is a basic workflow to help you get started with Actions

name: Debug AVA CI

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: ^14.15
      - name: Upgrade npm
        run: npm install --global npm@7
      - run: npm ci --no-audit
      - uses: mdelillo/ssh-server-action@v1
        with:
          ngrok-authtoken: ${{ secrets.NGROK_TOKEN }}
          ssh-public-key: ${{ secrets.DEBUG_SSH_PUBLIC_KEY }}
      - run: npm run cover
